### ISSUE TITLE
Milestone 1 Tasks

### ISSUE THREAD

**Issue by jasonrwang** [jasonrwang/SD-EnergyTransition#2]
Our first milestone is to have an operational model with sufficient formulas in each section that somewhat describe the system we are examining. Later, we can clean and incorporate data.

- [x] Make first diagram 
- [x] Put first diagram into Vensim

### Expand each submodel
- [ ] Transportation
- [ ] Residential Energy Consumption
- [ ] Electricity Production

### Find and document links between each
- [ ] Transportation
- [ ] Residential Energy Consumption
- [ ] Electricity Production

#### Transportation
- [ ] Hydrogen transition
- [ ] Electrification Rate
